theme: just-the-docs

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.png"

aux_links:
  "Github":
    - "https://github.com/rodrigoprestesmachado/ai"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 <a href='https://rpmhub.dev'>RPM Hub</a>. Distributed by CC-BY-4.0 license."